services:
  postgres:
    container_name: test_postgres_db
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432'