export const ALL_CURRENCY_COUNTRY_MAP = {
  'AUD': 'Australia',
  'BHD': 'Bahrain',
  'CAD': 'Canada',
  'CNY': 'China',
  'CZK': 'Czech Republic',
  'DKK': 'Denmark',
  'EUR': 'European Union',
  'HKD': 'Hong Kong',
  'HUF': 'Hungary',
  'INR': 'India',
  'IDR': 'Indonesia',
  'ILS': 'Israel',
  'JPY': 'Japan',
  'KES': 'Kenya',
  'KWD': 'Kuwait',
  'MYR': 'Malaysia',
  'MXN': 'Mexico',
  'NZD': 'New Zealand',
  'NOK': 'Norway',
  'OMR': 'Oman',
  'PHP': 'Philippines',
  'PLN': 'Poland',
  'QAR': 'Qatar',
  'RON': 'Romania',
  'SAR': 'Saudi Arabia',
  'SGD': 'Singapore',
  'ZAR': 'South Africa',
  'SEK': 'Sweden',
  'CHF': 'Switzerland',
  'THB': 'Thailand',
  'TRY': 'Turkey',
  'UGX': 'Uganda',
  'GBP': 'United Kingdom',
  'AED': 'United Arab Emirates',
  'USD': 'United States',
};

export default function useAllCountryName(currency) {
  return ALL_CURRENCY_COUNTRY_MAP[currency] || 'Unknown Country';
}