const CURRENCY_DESCRIPTION = {
  'AUD': "Australian Dollar",
  'BHD': "Bahrain Dinar",
  'CAD': "Canadian Dollar",
  'CNH': "Chinese Yuan",
  'CZK': "Czech Koruna",
  'DKK': 'Danish Krone',
  'EUR': 'European Euro',
  'HKD': "Hong Kong Dollar",
  'HUF': 'Hungarian Forint',
  'INR': 'Indian Rupee',
  'IDR': 'Indonesian Rupee',
  'ILS': 'Israel Shekel',
  'JPY': 'Japanese Yen',
  'KES': 'Kenyan Shilling',
  'KWD': 'Kuwait Dinar',
  'MYR': 'Malaysian Ringgit',
  'MXN': 'Mexican Peso',
  'NZD': 'New Zealand Dollar',
  'NOK': 'Norwegian Krone',
  'OMR': 'Oman Rial',
  'PHP': 'Philippine Peso',
  'PLN': 'Polish Zloty',
  'QAR': 'Qatar Rial',
  'RON': 'Romanian Leu',
  'SAR': 'Saudi Riyal',
  'SGD': 'Singapore Dollar',
  'ZAR': 'South African Rand',
  'SEK': 'Swedish Krona',
  'CHF': 'Swiss Franc',
  'THB': 'Thai Baht',
  'TRY': 'Turkish Lira',
  'UGX': 'Ugandan Shilling',
  'GBP': 'UK Sterling',
  'AED': 'UAE Dirham',
  'USD': 'US Dollar',
};

export default function useCurrencyDescription(currencyCode) {
  return CURRENCY_DESCRIPTION[currencyCode] || currencyCode;
}