-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public."Currency_Cloud" DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.token DROP CONSTRAINT IF EXISTS fkitpc2cx3eub3b0cvcakffdc3q;

ALTER TABLE IF EXISTS public.kyc DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public."Currency_Cloud";

CREATE TABLE IF NOT EXISTS public."Currency_Cloud"
(
    users_id bigint NOT NULL,
    "UUID" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Currency_Cloud_pkey" PRIMARY KEY ("UUID")
);

DROP TABLE IF EXISTS public._users;

CREATE TABLE IF NOT EXISTS public._users
(
    id bigint NOT NULL,
    address character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dob character varying(50) COLLATE pg_catalog."default" NOT NULL,
    firstname character varying(50) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(50) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT _users_pkey PRIMARY KEY (id),
    CONSTRAINT _users_email_key UNIQUE (email)
);

DROP TABLE IF EXISTS public.token;

CREATE TABLE IF NOT EXISTS public.token
(
    expired boolean NOT NULL,
    revoked boolean NOT NULL,
    id bigint NOT NULL,
    user_id bigint,
    token character varying(255) COLLATE pg_catalog."default",
    token_type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT token_pkey PRIMARY KEY (id),
    CONSTRAINT token_token_key UNIQUE (token)
);

DROP TABLE IF EXISTS public.kyc;

CREATE TABLE IF NOT EXISTS public.kyc
(
    key bigint NOT NULL,
    "Application_ID" character varying NOT NULL,
    "Work_Flow_Run_ID" character varying NOT NULL,
    "Status" character varying,
    user_id bigint NOT NULL,
    PRIMARY KEY (key)
);

ALTER TABLE IF EXISTS public."Currency_Cloud"
    ADD FOREIGN KEY (users_id)
    REFERENCES public._users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.token
    ADD CONSTRAINT fkitpc2cx3eub3b0cvcakffdc3q FOREIGN KEY (user_id)
    REFERENCES public._users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.kyc
    ADD FOREIGN KEY (user_id)
    REFERENCES public._users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;