--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3 (Ubuntu 16.3-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: _users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public._users (
    id bigint NOT NULL,
    address character varying(50) NOT NULL,
    dob character varying(50) NOT NULL,
    firstname character varying(50) NOT NULL,
    lastname character varying(50) NOT NULL,
    phone_number character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    role character varying(255),
    CONSTRAINT _users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'MANAGER'::character varying])::text[])))
);


--
-- Name: _users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public._users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public._users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: currency_cloud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.currency_cloud (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    uuid text NOT NULL
);


--
-- Name: currency_cloud_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.currency_cloud ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_cloud_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kyc; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kyc (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    application_id text NOT NULL,
    status text,
    work_flow_run_id text NOT NULL
);


--
-- Name: kyc_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.kyc ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kyc_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: _users _users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public._users
    ADD CONSTRAINT _users_email_key UNIQUE (email);


--
-- Name: _users _users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public._users
    ADD CONSTRAINT _users_pkey PRIMARY KEY (id);


--
-- Name: currency_cloud currency_cloud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currency_cloud
    ADD CONSTRAINT currency_cloud_pkey PRIMARY KEY (id);


--
-- Name: currency_cloud currency_cloud_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currency_cloud
    ADD CONSTRAINT currency_cloud_user_id_key UNIQUE (user_id);


--
-- Name: currency_cloud currency_cloud_uuid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currency_cloud
    ADD CONSTRAINT currency_cloud_uuid_key UNIQUE (uuid);


--
-- Name: kyc kyc_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kyc
    ADD CONSTRAINT kyc_pkey PRIMARY KEY (id);


--
-- Name: kyc kyc_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kyc
    ADD CONSTRAINT kyc_user_id_key UNIQUE (user_id);


--
-- Name: kyc fk2glwkicm9j3uvrvs7s38h4cth; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kyc
    ADD CONSTRAINT fk2glwkicm9j3uvrvs7s38h4cth FOREIGN KEY (user_id) REFERENCES public._users(id);


--
-- Name: currency_cloud fkdr949e7vjgcovg71uo42qmucl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currency_cloud
    ADD CONSTRAINT fkdr949e7vjgcovg71uo42qmucl FOREIGN KEY (user_id) REFERENCES public._users(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO backend_user;


--
-- PostgreSQL database dump complete
--

