name: Frontend CI

on:
  push:
    branches:
      - main
      - 'dev'
      - '**/frontend-**'

jobs:
  build-test:
    environment: Testing_Environment
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      RDS_SSL_CERT_PATH: ${{ secrets.RDS_SSL_CERT_PATH }}
      PEM_CONTENT: ${{ secrets.PEM_CONTENT }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Node modules
        id: cache-json
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node.js
        if: steps.cache-json.outputs.cache-hit != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Verify Cypress installation
        run: |
          cd frontend
          npx cypress verify

      - name: Build frontend
        run: |
          cd frontend
          npm run devReact &

      - name: Build backend
        run: |
          cd backend
          ./gradlew bootRun &

      - name: Cypress run
        run: |
          cd frontend
          npm run e2e:chrome

  report:
    needs: build-test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: |
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"
