-- INSERT INTO public.users (forename, surname, username, password, email, enabled)
-- VALUES
--     ('John', 'Doe', 'user', '$2a$10$uYFZi6xFtWxo5Xr7d/8OU.Y3b55MlXkPbZ01FwzW9TC8bljDFdF3y', 'user@example.com', true),
--     ('Jane', 'Smith', 'admin', '$2a$10$jZj3TQdVon9aR4eP5zBy0.wcVhlOHt8zEj72Z7c8z4t3t2XobD81u', 'admin@example.com', true);
--
--
-- INSERT INTO public.authorities (username, authority)
-- VALUES
--     ('user', 'ROLE_USER'),
--     ('admin', 'ROLE_ADMIN');